spring:
  application:
    name: greeting-service

server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'  
greeting-service:
  greeting: "Ola-QA"
  default-value: "Mundo"